/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    events: Event;
    galleries: Gallery;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    galleries: GalleriesSelect<false> | GalleriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    homepage: Homepage;
    navigation: Navigation;
    'community-faq': CommunityFaq;
    'legal-impressum': LegalImpressum;
    'legal-datenschutz': LegalDatenschutz;
    'cookie-banner': CookieBanner;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    'community-faq': CommunityFaqSelect<false> | CommunityFaqSelect<true>;
    'legal-impressum': LegalImpressumSelect<false> | LegalImpressumSelect<true>;
    'legal-datenschutz': LegalDatenschutzSelect<false> | LegalDatenschutzSelect<true>;
    'cookie-banner': CookieBannerSelect<false> | CookieBannerSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Zentrale Bilddateien. Alt-Texte sind Pflicht fuer Barrierefreiheit und SEO; sie werden bei next/image und Screenreadern genutzt.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Kurze Bildbeschreibung (was zu sehen ist). Wird als alt-Attribut ausgespielt — nicht keyword-stuffen, sondern inhaltlich treffend.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Events erscheinen in der Liste unter /events und als Detailseite unter /events/<slug>. Bilder und Startseiten-Hero-Felder steuern zusaetzlich die Startseite.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  /**
   * Oeffentlicher Event-Name. Wird auf Karten, der Event-Seite und — falls kein Meta-Titel gesetzt ist — im Browser-Tab verwendet.
   */
  title: string;
  /**
   * URL-Pfad ohne Schraegstriche und Leerzeichen: nur Kleinbuchstaben, Zahlen und Bindestriche (z. B. birstein-19-4-2026). Im Web: https://…/events/<slug> — der Slug ist der letzte Teil der Adresse.
   */
  slug: string;
  /**
   * Datum und optional Uhrzeit (Kalender-Export und Event-Seite). Ohne Uhrzeit = ganztägig im Kalender.
   */
  date: string;
  /**
   * Kurzer Orts- oder Treffpunkt-Text auf der Event-Seite und in Snippets, wenn keine eigene Meta-Beschreibung gesetzt ist.
   */
  location: string;
  /**
   * Optionale vollständige Adresse (Straße, PLZ Ort). Wird in Kalender-Einträgen (ICS / Google) zusätzlich zum Treffpunkt übernommen.
   */
  address?: string | null;
  /**
   * «Abgesagt» blendet das Event auf der öffentlichen Übersicht und im Kalender-Feed aus; die Detail-URL bleibt erreichbar. «Ausverkauft» zeigt ein Badge, bleibt aber sichtbar.
   */
  status: 'planned' | 'confirmed' | 'sold_out' | 'cancelled';
  /**
   * Kurze Fragen und Antworten zur Event-Seite (z. B. Anmeldung, Treffpunkt).
   */
  faq?:
    | {
        /**
         * Frage (kurz).
         */
        question: string;
        /**
         * Antwort — ein bis zwei Sätze reichen oft.
         */
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Stichpunkte «Was mitbringen» (z. B. Ausweis, Wetterjacke).
   */
  bringList?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Galerie auf der Event-Detailseite. Reihenfolge entspricht der Anzeige; erstes Bild wird oft als Hauptmotiv genutzt.
   */
  images?: (number | Media)[] | null;
  /**
   * Erscheint im Browser-Tab und als Hauptzeile in Suchergebnissen. Leer = automatisch der Eventtitel plus «| DriversClub Hessen».
   */
  metaTitle?: string | null;
  /**
   * Kurzer Teaser unter dem Titel in Suchergebnissen (ca. 150–160 Zeichen empfohlen). Beeinflusst die Klickrate, nicht direkt das Ranking. Leer = automatische Zeile aus Titel, Datum und Ort.
   */
  metaDescription?: string | null;
  /**
   * Wenn dieses Event das naechste anstehende ist, ersetzt es die Hero-Inhalte der Startseite (Titel, Countdown, optional Hintergrund). Leere Felder nutzen sinnvolle Standardwerte aus Titel und Datum.
   */
  homepageHero?: {
    /**
     * Kleine Zeile ueber dem grossen Titel im Hero auf der Startseite.
     */
    eyebrow?: string | null;
    /**
     * Erste grosse Titelzeile im Startseiten-Hero.
     */
    titleLine1?: string | null;
    /**
     * Zweite grosse Titelzeile im Startseiten-Hero (oft Akzent-Wort).
     */
    titleLine2?: string | null;
    /**
     * Steht unter dem Titel, z. B. formatiertes Datum. Leer = automatisch aus Event-Datum.
     */
    dateLabel?: string | null;
    /**
     * Datum und Uhrzeit fuer den Countdown. Leer = Event-Datum um 12:00 Uhr.
     */
    countdownEnd?: string | null;
    /**
     * Kompaktes Label im Hero (z. B. Event-Name oder Sponsoring).
     */
    badge?: string | null;
    /**
     * Text unter den Buttons im Hero.
     */
    tagline?: string | null;
    /**
     * Call-to-Actions im Startseiten-Hero. «Intern (Event)» verlinkt auf /events/<slug> des gewaehlten Events.
     */
    ctas?:
      | {
          /**
           * Beschriftung auf dem Button im Hero.
           */
          label: string;
          /**
           * Intern: waehle ein Event aus der Liste. Extern: vollstaendige URL (oeffnet in neuem Tab).
           */
          linkMode: 'reference' | 'external';
          eventReference?: (number | null) | Event;
          /**
           * z. B. https://instagram.com/…
           */
          externalUrl?: string | null;
          /**
           * Visuelle Button-Variante (gefuellt vs. Umrandung).
           */
          variant?: ('primary' | 'outline') | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Grossflaechiges Hero-Hintergrundbild auf der Startseite (LCP-relevant).
     */
    backgroundImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Einzelbilder fuer die Galerie-Seite unter /gallery. Veroeffentlichte Eintraege erscheinen im Raster; Entwuerfe nicht.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "galleries".
 */
export interface Gallery {
  id: number;
  /**
   * Bildunterschrift / Titel unter dem Foto auf /gallery.
   */
  title: string;
  /**
   * Das angezeigte Galerie-Bild. Alt-Text kommt aus dem Medien-Eintrag.
   */
  image: number | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'galleries';
        value: number | Gallery;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  date?: T;
  location?: T;
  address?: T;
  status?: T;
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  bringList?:
    | T
    | {
        item?: T;
        id?: T;
      };
  images?: T;
  metaTitle?: T;
  metaDescription?: T;
  homepageHero?:
    | T
    | {
        eyebrow?: T;
        titleLine1?: T;
        titleLine2?: T;
        dateLabel?: T;
        countdownEnd?: T;
        badge?: T;
        tagline?: T;
        ctas?:
          | T
          | {
              label?: T;
              linkMode?: T;
              eventReference?: T;
              externalUrl?: T;
              variant?: T;
              id?: T;
            };
        backgroundImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "galleries_select".
 */
export interface GalleriesSelect<T extends boolean = true> {
  title?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Startseiten-Layout (Blockreihenfolge) und SEO-Felder fuer /, /events, /gallery. Aenderungen wirken nach Veroeffentlichung und Revalidierung auf die Live-Site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  /**
   * Reihenfolge der Blöcke = Reihenfolge auf der Startseite. Leer = Standard-Fallback aus dem Frontend.
   */
  layout?:
    | (
        | HomepageHeroBlock
        | HomepageTickerBlock
        | HomepageEventBlock
        | HomepageFeaturesBlock
        | HomepageRulesBlock
        | HomepageAboutBlock
        | HomepageLocationBlock
        | HomepageSocialBlock
      )[]
    | null;
  /**
   * Browser-Tab und Hauptzeile in Suchergebnissen fuer die Startseite.
   */
  homeMetaTitle?: string | null;
  /**
   * Kurztext in Snippets (ca. 150–160 Zeichen). Leer = Standardbeschreibung der Site aus dem Code.
   */
  homeMetaDescription?: string | null;
  /**
   * Titel fuer die Events-Uebersicht im Tab und in Suchmaschinen.
   */
  eventsIndexMetaTitle?: string | null;
  /**
   * Snippet-Text fuer /events. Leer = Standardtext der Events-Seite.
   */
  eventsIndexMetaDescription?: string | null;
  /**
   * Titel fuer die Galerie-Uebersicht.
   */
  galleryMetaTitle?: string | null;
  /**
   * Snippet-Text fuer die Galerie. Leer = Standardtext der Galerie-Seite.
   */
  galleryMetaDescription?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomepageHeroBlock".
 */
export interface HomepageHeroBlock {
  /**
   * Hero (Titel, Countdown, CTAs, Hintergrund, …) kommt aus dem Event-Dokument → Gruppe „Startseiten-Hero“. Leer = naechstes anstehendes Event aus der Liste. Wenn kein Event verfuegbar ist, nutzt das Frontend feste Fallback-Texte.
   */
  heroEvent?: (number | null) | Event;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomepageTickerBlock".
 */
export interface HomepageTickerBlock {
  /**
   * Lauftext-Zeilen unter dem Hero. Reihenfolge = Darstellungsreihenfolge.
   */
  items?:
    | {
        /**
         * Eine Zeile im Ticker (kurz halten).
         */
        text: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ticker';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomepageEventBlock".
 */
export interface HomepageEventBlock {
  /**
   * Kleine Ueberschrift ueber dem Abschnitt.
   */
  sectionLabel?: string | null;
  /**
   * Titel-Anfang (normale Schrift).
   */
  titleLead?: string | null;
  /**
   * Titel-Akzentteil (hervorgehoben).
   */
  titleAccent?: string | null;
  /**
   * Anzeige wenn keine Events aus der Datenbank geladen werden.
   */
  infoCards?:
    | {
        icon: string;
        title: string;
        value: string;
        sub: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Daten fuer den Event-Teaser (wenn die Seite Events aus der API laedt). Info-Karten darueber gelten als Fallback ohne API-Daten.
   */
  featuredEvent?: (number | null) | Event;
  id?: string | null;
  blockName?: string | null;
  blockType: 'event';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomepageFeaturesBlock".
 */
export interface HomepageFeaturesBlock {
  /**
   * Kleine Ueberschrift ueber dem Abschnitt.
   */
  sectionLabel?: string | null;
  /**
   * Titel-Anfang.
   */
  titleLead?: string | null;
  /**
   * Titel-Akzent.
   */
  titleAccent?: string | null;
  /**
   * Kacheln im Highlights-Bereich der Startseite.
   */
  items?:
    | {
        /**
         * Kurzes Emoji oder Symbol neben dem Titel.
         */
        icon?: string | null;
        /**
         * Optional: ersetzt oder ergaenzt das Text-Icon.
         */
        iconImage?: (number | null) | Media;
        /**
         * Feature-Ueberschrift.
         */
        title: string;
        /**
         * Kurzer Erklaertext unter dem Titel.
         */
        description: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'features';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomepageRulesBlock".
 */
export interface HomepageRulesBlock {
  /**
   * Kleine Ueberschrift.
   */
  sectionLabel?: string | null;
  /**
   * Titel-Anfang.
   */
  titleLead?: string | null;
  /**
   * Titel-Akzent.
   */
  titleAccent?: string | null;
  /**
   * Aufzaehlung der Verhaltens-/Treffen-Regeln auf der Startseite.
   */
  items?:
    | {
        /**
         * Kleines Symbol vor dem Regeltext.
         */
        icon?: string | null;
        /**
         * Formulierung der Regel.
         */
        text: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'rules';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomepageAboutBlock".
 */
export interface HomepageAboutBlock {
  /**
   * Kleine Ueberschrift.
   */
  sectionLabel?: string | null;
  /**
   * Titel-Anfang.
   */
  titleLead?: string | null;
  /**
   * Titel-Akzent.
   */
  titleAccent?: string | null;
  /**
   * Kleines Label in der linken Spalte.
   */
  leftBadge?: string | null;
  /**
   * Name / Titel in der linken Spalte.
   */
  leftName?: string | null;
  /**
   * Kleines Label in der rechten Spalte.
   */
  rightBadge?: string | null;
  /**
   * Name / Titel in der rechten Spalte.
   */
  rightName?: string | null;
  /**
   * Fliesstext im «Ueber uns»-Bereich zwischen den beiden Spalten.
   */
  body?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'about';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomepageLocationBlock".
 */
export interface HomepageLocationBlock {
  /**
   * Kleine Ueberschrift.
   */
  sectionLabel?: string | null;
  /**
   * Titel-Anfang.
   */
  titleLead?: string | null;
  /**
   * Titel-Akzent.
   */
  titleAccent?: string | null;
  /**
   * Link, der beim Klick auf die Karte geoeffnet wird (vollstaendige https://… URL).
   */
  mapUrl?: string | null;
  /**
   * Statisches Vorschaubild statt eingebetteter Karte.
   */
  mapImage?: (number | null) | Media;
  /**
   * Optional: strukturierte Infos (Adresse, Zeiten, …). Leer = Standard-Fallback im Frontend.
   */
  rows?:
    | {
        icon?: string | null;
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'location';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomepageSocialBlock".
 */
export interface HomepageSocialBlock {
  /**
   * Kleine Ueberschrift.
   */
  sectionLabel?: string | null;
  /**
   * Titel-Anfang.
   */
  titleLead?: string | null;
  /**
   * Titel-Akzent.
   */
  titleAccent?: string | null;
  /**
   * Kurzer Text vor der Link-Liste.
   */
  intro?: string | null;
  /**
   * Social- oder externe Links im Footer-Bereich der Startseite.
   */
  links?:
    | {
        /**
         * Sichtbarer Link-Text.
         */
        label: string;
        /**
         * Ziel-URL mit https:// (z. B. Instagram, TikTok).
         */
        url: string;
        /**
         * Externe Seiten typischerweise in neuem Tab.
         */
        openInNewTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'social';
}
/**
 * Header-Navigation der Marketing-Site. Interne Ziele werden zu festen URLs (inkl. Anker auf der Startseite).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * Hauptnavigation (Header). Interne Ziele entsprechen den Marketing-Routen in dieser App.
   */
  items?:
    | {
        /**
         * Sichtbarer Text im Menue.
         */
        label: string;
        /**
         * Intern: Seite oder Anker in dieser App. Extern: beliebige URL (z. B. Social).
         */
        linkType: 'internal' | 'external';
        /**
         * Startseite → / · Aktuell → /#aktuell · Ueber uns → /#about · Anfahrt → /#location · Social → /#social · Events → /events · Galerie → /gallery · FAQ → /faq · Impressum → /legal/impressum · Datenschutz → /legal/datenschutz
         */
        internalTarget?:
          | (
              | 'home'
              | 'homeEvent'
              | 'homeAbout'
              | 'homeLocation'
              | 'homeSocial'
              | 'events'
              | 'gallery'
              | 'faq'
              | 'impressum'
              | 'datenschutz'
            )
          | null;
        /**
         * Vollständige URL, z. B. https://instagram.com/…
         */
        externalUrl?: string | null;
        openInNewTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Inhalt der Seite /faq (Regeln, Gruppenstruktur, Partner). Leer = festes Fallback aus dem Frontend.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "community-faq".
 */
export interface CommunityFaq {
  id: number;
  /**
   * H1 auf /faq.
   */
  title: string;
  /**
   * Kurztext für Suchmaschinen / Social. Leer = Standardbeschreibung aus dem Code.
   */
  metaDescription?: string | null;
  /**
   * Wenn gesetzt, ersetzt dieser Block den Standard-Text aus dem Frontend vollständig.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Inhalt der Seite /legal/impressum (Titel + Rich Text).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-impressum".
 */
export interface LegalImpressum {
  id: number;
  /**
   * Seitenueberschrift auf /legal/impressum.
   */
  title: string;
  /**
   * Rechtlicher Impressum-Text (wird auf der Impressum-Route gerendert).
   */
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Inhalt der Seite /legal/datenschutz (Titel + Rich Text).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-datenschutz".
 */
export interface LegalDatenschutz {
  id: number;
  /**
   * Seitenueberschrift auf /legal/datenschutz.
   */
  title: string;
  /**
   * Datenschutzerklaerung (wird auf der Datenschutz-Route gerendert).
   */
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Texte und Schaltflaechen des Cookie-Hinweises (erscheint auf allen Marketing-Seiten bis zur Entscheidung).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cookie-banner".
 */
export interface CookieBanner {
  id: number;
  /**
   * Haupttext im Banner-Dialog.
   */
  message: string;
  /**
   * Beschriftung der Zustimmen-Schaltflaeche.
   */
  acceptLabel?: string | null;
  /**
   * Beschriftung fuer ablehnen / nur notwendige Cookies.
   */
  rejectLabel?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  layout?:
    | T
    | {
        hero?: T | HomepageHeroBlockSelect<T>;
        ticker?: T | HomepageTickerBlockSelect<T>;
        event?: T | HomepageEventBlockSelect<T>;
        features?: T | HomepageFeaturesBlockSelect<T>;
        rules?: T | HomepageRulesBlockSelect<T>;
        about?: T | HomepageAboutBlockSelect<T>;
        location?: T | HomepageLocationBlockSelect<T>;
        social?: T | HomepageSocialBlockSelect<T>;
      };
  homeMetaTitle?: T;
  homeMetaDescription?: T;
  eventsIndexMetaTitle?: T;
  eventsIndexMetaDescription?: T;
  galleryMetaTitle?: T;
  galleryMetaDescription?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomepageHeroBlock_select".
 */
export interface HomepageHeroBlockSelect<T extends boolean = true> {
  heroEvent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomepageTickerBlock_select".
 */
export interface HomepageTickerBlockSelect<T extends boolean = true> {
  items?:
    | T
    | {
        text?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomepageEventBlock_select".
 */
export interface HomepageEventBlockSelect<T extends boolean = true> {
  sectionLabel?: T;
  titleLead?: T;
  titleAccent?: T;
  infoCards?:
    | T
    | {
        icon?: T;
        title?: T;
        value?: T;
        sub?: T;
        id?: T;
      };
  featuredEvent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomepageFeaturesBlock_select".
 */
export interface HomepageFeaturesBlockSelect<T extends boolean = true> {
  sectionLabel?: T;
  titleLead?: T;
  titleAccent?: T;
  items?:
    | T
    | {
        icon?: T;
        iconImage?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomepageRulesBlock_select".
 */
export interface HomepageRulesBlockSelect<T extends boolean = true> {
  sectionLabel?: T;
  titleLead?: T;
  titleAccent?: T;
  items?:
    | T
    | {
        icon?: T;
        text?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomepageAboutBlock_select".
 */
export interface HomepageAboutBlockSelect<T extends boolean = true> {
  sectionLabel?: T;
  titleLead?: T;
  titleAccent?: T;
  leftBadge?: T;
  leftName?: T;
  rightBadge?: T;
  rightName?: T;
  body?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomepageLocationBlock_select".
 */
export interface HomepageLocationBlockSelect<T extends boolean = true> {
  sectionLabel?: T;
  titleLead?: T;
  titleAccent?: T;
  mapUrl?: T;
  mapImage?: T;
  rows?:
    | T
    | {
        icon?: T;
        label?: T;
        value?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomepageSocialBlock_select".
 */
export interface HomepageSocialBlockSelect<T extends boolean = true> {
  sectionLabel?: T;
  titleLead?: T;
  titleAccent?: T;
  intro?: T;
  links?:
    | T
    | {
        label?: T;
        url?: T;
        openInNewTab?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        linkType?: T;
        internalTarget?: T;
        externalUrl?: T;
        openInNewTab?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "community-faq_select".
 */
export interface CommunityFaqSelect<T extends boolean = true> {
  title?: T;
  metaDescription?: T;
  body?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-impressum_select".
 */
export interface LegalImpressumSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-datenschutz_select".
 */
export interface LegalDatenschutzSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cookie-banner_select".
 */
export interface CookieBannerSelect<T extends boolean = true> {
  message?: T;
  acceptLabel?: T;
  rejectLabel?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}