/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    events: Event;
    galleries: Gallery;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    galleries: GalleriesSelect<false> | GalleriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    homepage: Homepage;
    navigation: Navigation;
    'legal-impressum': LegalImpressum;
    'legal-datenschutz': LegalDatenschutz;
    'cookie-banner': CookieBanner;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    'legal-impressum': LegalImpressumSelect<false> | LegalImpressumSelect<true>;
    'legal-datenschutz': LegalDatenschutzSelect<false> | LegalDatenschutzSelect<true>;
    'cookie-banner': CookieBannerSelect<false> | CookieBannerSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Meta-Titel und -Beschreibung pro Route. Slug **home** = Startseite; sonst ohne Domain und ohne führenden Slash (z. B. events, gallery, legal/impressum, events/dein-event-slug).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * **home** für die Startseite. Beispiele: **events**, **gallery**, **legal/impressum**, **events/meet-2026**.
   */
  slug: string;
  /**
   * Optional. Leer = Standard aus dem Code für diese Route.
   */
  metaTitle?: string | null;
  /**
   * Empfohlen bis ca. 160 Zeichen.
   */
  metaDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  slug: string;
  date: string;
  location: string;
  images?: (number | Media)[] | null;
  /**
   * Wenn dieses Event das naechste anstehende ist, ersetzt es die Hero-Inhalte der Startseite (Titel, Countdown, optional Hintergrund). Leere Felder nutzen sinnvolle Standardwerte aus Titel und Datum.
   */
  homepageHero?: {
    eyebrow?: string | null;
    titleLine1?: string | null;
    titleLine2?: string | null;
    /**
     * Steht unter dem Titel, z. B. formatiertes Datum. Leer = automatisch aus Event-Datum.
     */
    dateLabel?: string | null;
    /**
     * Datum und Uhrzeit fuer den Countdown. Leer = Event-Datum um 12:00 Uhr.
     */
    countdownEnd?: string | null;
    badge?: string | null;
    tagline?: string | null;
    ctas?:
      | {
          label: string;
          /**
           * Intern: waehle ein Event aus der Liste. Extern: vollstaendige URL (oeffnet in neuem Tab).
           */
          linkMode: 'reference' | 'external';
          eventReference?: (number | null) | Event;
          /**
           * z. B. https://instagram.com/…
           */
          externalUrl?: string | null;
          variant?: ('primary' | 'outline') | null;
          id?: string | null;
        }[]
      | null;
    backgroundImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "galleries".
 */
export interface Gallery {
  id: number;
  title: string;
  image: number | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'galleries';
        value: number | Gallery;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  slug?: T;
  metaTitle?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  date?: T;
  location?: T;
  images?: T;
  homepageHero?:
    | T
    | {
        eyebrow?: T;
        titleLine1?: T;
        titleLine2?: T;
        dateLabel?: T;
        countdownEnd?: T;
        badge?: T;
        tagline?: T;
        ctas?:
          | T
          | {
              label?: T;
              linkMode?: T;
              eventReference?: T;
              externalUrl?: T;
              variant?: T;
              id?: T;
            };
        backgroundImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "galleries_select".
 */
export interface GalleriesSelect<T extends boolean = true> {
  title?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  /**
   * Reihenfolge der Blöcke = Reihenfolge auf der Startseite. Leer = Standard-Fallback aus dem Frontend.
   */
  layout?:
    | (
        | HomepageHeroBlock
        | HomepageTickerBlock
        | HomepageEventBlock
        | HomepageFeaturesBlock
        | HomepageRulesBlock
        | HomepageAboutBlock
        | HomepageLocationBlock
        | HomepageSocialBlock
      )[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomepageHeroBlock".
 */
export interface HomepageHeroBlock {
  /**
   * Fallback-Hero, wenn kein anstehendes Event existiert. Sobald ein Event ansteht, uebernimmt das naechste Event die Hero-Inhalte (siehe Event → Startseiten-Hero).
   */
  eyebrow: string;
  titleLine1: string;
  titleLine2: string;
  dateLabel: string;
  countdownEnd?: string | null;
  badge?: string | null;
  tagline?: string | null;
  ctas?:
    | {
        label: string;
        /**
         * Intern: waehle ein Event aus der Liste. Extern: vollstaendige URL (oeffnet in neuem Tab).
         */
        linkMode: 'reference' | 'external';
        eventReference?: (number | null) | Event;
        /**
         * z. B. https://instagram.com/…
         */
        externalUrl?: string | null;
        variant?: ('primary' | 'outline') | null;
        id?: string | null;
      }[]
    | null;
  backgroundImage?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomepageTickerBlock".
 */
export interface HomepageTickerBlock {
  items?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ticker';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomepageEventBlock".
 */
export interface HomepageEventBlock {
  sectionLabel?: string | null;
  titleLead?: string | null;
  titleAccent?: string | null;
  /**
   * Anzeige wenn keine Events aus der Datenbank geladen werden.
   */
  infoCards?:
    | {
        icon: string;
        title: string;
        value: string;
        sub: string;
        id?: string | null;
      }[]
    | null;
  featuredEvent?: (number | null) | Event;
  id?: string | null;
  blockName?: string | null;
  blockType: 'event';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomepageFeaturesBlock".
 */
export interface HomepageFeaturesBlock {
  sectionLabel?: string | null;
  titleLead?: string | null;
  titleAccent?: string | null;
  items?:
    | {
        icon?: string | null;
        iconImage?: (number | null) | Media;
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'features';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomepageRulesBlock".
 */
export interface HomepageRulesBlock {
  sectionLabel?: string | null;
  titleLead?: string | null;
  titleAccent?: string | null;
  items?:
    | {
        icon?: string | null;
        text: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'rules';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomepageAboutBlock".
 */
export interface HomepageAboutBlock {
  sectionLabel?: string | null;
  titleLead?: string | null;
  titleAccent?: string | null;
  leftBadge?: string | null;
  leftName?: string | null;
  rightBadge?: string | null;
  rightName?: string | null;
  body?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'about';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomepageLocationBlock".
 */
export interface HomepageLocationBlock {
  sectionLabel?: string | null;
  titleLead?: string | null;
  titleAccent?: string | null;
  mapUrl?: string | null;
  mapImage?: (number | null) | Media;
  /**
   * Optional: strukturierte Infos (Adresse, Zeiten, …). Leer = Standard-Fallback im Frontend.
   */
  rows?:
    | {
        icon?: string | null;
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'location';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomepageSocialBlock".
 */
export interface HomepageSocialBlock {
  sectionLabel?: string | null;
  titleLead?: string | null;
  titleAccent?: string | null;
  intro?: string | null;
  links?:
    | {
        label: string;
        url: string;
        openInNewTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'social';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * Hauptnavigation (Header). Interne Ziele entsprechen den Marketing-Routen in dieser App.
   */
  items?:
    | {
        label: string;
        linkType: 'internal' | 'external';
        internalTarget?:
          | (
              | 'home'
              | 'homeEvent'
              | 'homeAbout'
              | 'homeLocation'
              | 'homeSocial'
              | 'events'
              | 'gallery'
              | 'impressum'
              | 'datenschutz'
            )
          | null;
        /**
         * Vollständige URL, z. B. https://instagram.com/…
         */
        externalUrl?: string | null;
        openInNewTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-impressum".
 */
export interface LegalImpressum {
  id: number;
  title: string;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-datenschutz".
 */
export interface LegalDatenschutz {
  id: number;
  title: string;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cookie-banner".
 */
export interface CookieBanner {
  id: number;
  message: string;
  acceptLabel?: string | null;
  rejectLabel?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  layout?:
    | T
    | {
        hero?: T | HomepageHeroBlockSelect<T>;
        ticker?: T | HomepageTickerBlockSelect<T>;
        event?: T | HomepageEventBlockSelect<T>;
        features?: T | HomepageFeaturesBlockSelect<T>;
        rules?: T | HomepageRulesBlockSelect<T>;
        about?: T | HomepageAboutBlockSelect<T>;
        location?: T | HomepageLocationBlockSelect<T>;
        social?: T | HomepageSocialBlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomepageHeroBlock_select".
 */
export interface HomepageHeroBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  titleLine1?: T;
  titleLine2?: T;
  dateLabel?: T;
  countdownEnd?: T;
  badge?: T;
  tagline?: T;
  ctas?:
    | T
    | {
        label?: T;
        linkMode?: T;
        eventReference?: T;
        externalUrl?: T;
        variant?: T;
        id?: T;
      };
  backgroundImage?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomepageTickerBlock_select".
 */
export interface HomepageTickerBlockSelect<T extends boolean = true> {
  items?:
    | T
    | {
        text?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomepageEventBlock_select".
 */
export interface HomepageEventBlockSelect<T extends boolean = true> {
  sectionLabel?: T;
  titleLead?: T;
  titleAccent?: T;
  infoCards?:
    | T
    | {
        icon?: T;
        title?: T;
        value?: T;
        sub?: T;
        id?: T;
      };
  featuredEvent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomepageFeaturesBlock_select".
 */
export interface HomepageFeaturesBlockSelect<T extends boolean = true> {
  sectionLabel?: T;
  titleLead?: T;
  titleAccent?: T;
  items?:
    | T
    | {
        icon?: T;
        iconImage?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomepageRulesBlock_select".
 */
export interface HomepageRulesBlockSelect<T extends boolean = true> {
  sectionLabel?: T;
  titleLead?: T;
  titleAccent?: T;
  items?:
    | T
    | {
        icon?: T;
        text?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomepageAboutBlock_select".
 */
export interface HomepageAboutBlockSelect<T extends boolean = true> {
  sectionLabel?: T;
  titleLead?: T;
  titleAccent?: T;
  leftBadge?: T;
  leftName?: T;
  rightBadge?: T;
  rightName?: T;
  body?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomepageLocationBlock_select".
 */
export interface HomepageLocationBlockSelect<T extends boolean = true> {
  sectionLabel?: T;
  titleLead?: T;
  titleAccent?: T;
  mapUrl?: T;
  mapImage?: T;
  rows?:
    | T
    | {
        icon?: T;
        label?: T;
        value?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomepageSocialBlock_select".
 */
export interface HomepageSocialBlockSelect<T extends boolean = true> {
  sectionLabel?: T;
  titleLead?: T;
  titleAccent?: T;
  intro?: T;
  links?:
    | T
    | {
        label?: T;
        url?: T;
        openInNewTab?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        linkType?: T;
        internalTarget?: T;
        externalUrl?: T;
        openInNewTab?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-impressum_select".
 */
export interface LegalImpressumSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-datenschutz_select".
 */
export interface LegalDatenschutzSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cookie-banner_select".
 */
export interface CookieBannerSelect<T extends boolean = true> {
  message?: T;
  acceptLabel?: T;
  rejectLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}